# Utilisez l'image Python officielle
FROM python:3.8

# Définissez le répertoire de travail
WORKDIR /app

# Copiez le contenu du répertoire backend dans le conteneur
COPY . .

# Copiez le fichier requirements.txt
COPY requirements.txt .

# Mise à jour de pip
RUN pip install --upgrade pip

# Installez les dépendances
RUN pip install -r requirements.txt

# Exposez le port sur lequel l'application Flask écoute
EXPOSE 5000

# Commande pour exécuter l'application Flask
CMD ["python", "app.py"]
